- name: Install PHP
  apt:
    name="{{ item }}"
    state=present
  with_items:
    - php5-fpm
    - php5
    - php-pear
    - php5-mysql
    - php5-gd
  become: yes

- name: Create destination folder
  file:
    path: "{{ dest }}"
    state: directory
    owner: "{{ server_user }}"
    group: "{{ server_group }}"
    mode: 0755
  become: yes
  become_user: "{{ server_user }}"

- name: Clone git yii repo
  git:
    repo: "{{ repo }}"
    dest: "{{ dest }}"
    version: "{{ version  }}"
    update: yes
    force: yes
    recursive: yes
    accept_hostkey: yes
  become: yes
  become_user: "{{ server_user }}"
  when: repo is defined
  tags: update_yii_repo

- name: Add git config repo to update remote
  command: "git config receive.denyCurrentBranch updateInstead"
  args:
    chdir: "{{ dest }}"

- name: Composer | Install
  command: php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
  args:
    chdir: "{{ dest }}"
    creates: "{{ dest }}/composer-setup.php"
  become: yes
  become_user: "{{ server_user }}"
  tags:
    - update_yii_repo

- name: Composer | Setup
  command: php composer-setup.php
  args:
    chdir: "{{ dest }}"
    creates: "{{ dest }}/composer.phar"
  become: yes
  become_user: "{{ server_user }}"
  tags:
    - update_yii_repo

- name: Install Yii2 dependencies
  shell: 'php composer.phar global require "fxp/composer-asset-plugin"'
  args:
    chdir: "{{ dest }}"
    creates: "/home/{{ server_user }}/.composer/vendor"
  become: yes
  become_user: "{{ server_user }}"
  when: repo is defined
  tags:
    - update_yii_repo

- name: Update dependencies for repo. This may take a while . . . . .
  shell: "php composer.phar update -n {{ yii_extra_flags }}"
  args:
    chdir: "{{ dest }}"
    creates: "{{ dest }}/vendor"
  become: yes
  become_user: "{{ server_user }}"
  retries: 4
  register: command_result
  when: repo is defined
  tags: update_yii_repo
  ignore_errors: yes

- name: Log dependencies errors if any
  local_action:
    module: lineinfile
    dest: /opt/tinker/shared_files/logs/fail.log
    line: "{{ ansible_date_time.date }} {{ ansible_date_time.time }} {{ command_result.stdout }}"
    create: yes
  when: '"Problem 1" in command_result.stdout'
  tags:
    - update_services
    - update_yii_repo
  become: yes
  become_user: "{{ server_user }}"

- name: Ensure correct folder permissions
  file:
    path: "{{ item }}"
    mode: 0777
  become: yes
  with_items:
    - "{{ dest }}/runtime"
    - "{{ dest }}/web/assets"

- name: Write custom NGINX configuration
  template:
    src: vhosts.conf
    dest: /etc/nginx/sites-enabled/vhosts.conf
    owner: root
    group: root
    mode: 0644
  become: yes
